### ISSUE TITLE
Why upload a zip?

### ISSUE THREAD

**Issue by NathanSalapat** [BubbaFrog/Rangedweapons-Remasterd#1]
The whole point of using git is that you can see all the individual files. Anybody that downloads this has to extract the zip file and rename stuff. Also you have a license file saying cc-by-sa 4.0 but the readme says you don't own all the content. You should list what content you created that has that license. What's the license of the minecraft mod assets you use, can you legal redistribute them?
Just some things you should look into. :)

**Comment by BubbaFrog** [comment]
heres the link for the licence of the minecraft mod i used it was only 1 mod https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/blob/master/LICENSE

**Comment by BubbaFrog** [comment]
heres an list of minetest mods i used to make it                                                                                                                                                       https://github.com/D00Med/mobs_scifi                                                                                                                               https://github.com/N-nec/rangedweapons-Dog-Wars                                                                                                           https://github.com/LoneWolfHT/artillery                                                                                                                             https://github.com/daviddoesminetest/testventure                                                                                                              https://github.com/daviddoesminetest/Xtraores-                                                                                                                            https://github.com/daviddoesminetest/Minerdream_mod                                                                                                         https://github.com/daviddoesminetest/rangedweapons                                                                                           https://forum.minetest.net/viewtopic.php?t=7567                                                                                                                https://github.com/natelastname/ctf_guns/tree/master/ctf_ranged                                                                                               https://github.com/starninjas/fguns                                                                                                                                        https://github.com/AiTechEye/vexcazer                                                                                                                              https://github.com/AiTechEye/portalgun                                                                                                                                https://github.com/AiTechEye/gravitygun                                                                                                                                https://github.com/BrunoMine/musket

**Comment by BubbaFrog** [comment]
i mean like how to an folder inside another folder

**Comment by BubbaFrog** [comment]
thank you for the help tho

**Comment by NathanSalapat** [comment]
If you're not familiar with using the command line I'd recommend downloading Github Desktop, https://desktop.github.com/ it makes it really easy to add content.
Basically you'd download and install GitHub desktop and then add a local repository, selecting your mod, as it exists in your mod folder. All the files are then automatically tracked and added, so when you commit the exact layout is uploaded.

It looks like the minecraft mod is licensed GPL so any content you pulled from there you should list in a license or readme file listing the file names you have and that they are licensed by Hbm as GPL. Or whomever is behind that repository. You'd do the same thing for all the content you borrowed from Minetest mods. Check to see the licenses used and who holds them, and then credit all the media accordingly. It sounds like a lot of work, but it really isn't so bad, and you legally do need to include that information.

**Comment by BubbaFrog** [comment]
ok so i updated the mod is the readme a pretty good credit to give
